version: '3.8'

services:
  app:
    build: .
    container_name: viking-node-app
    ports:
      - "18080:8080"
    environment:
      - NODE_ENV=production
      - DB_HOST=host.docker.internal         # ✅ bu yer to‘g‘ridan-to‘g‘ri Postgres servisini bildiradi
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=root123
      - DB_NAME=viking_pay
    depends_on:
      - db
    restart: always